application: PythonPractice
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: home.app

- url: /.*
  script: updateLocation.py

libraries:
- name: numpy
  version: "latest"